// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class Cidade
    {
        public Cidade()
        {
            Endereco = new HashSet<Endereco>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idEstado")]
        public int IdEstado { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(256)]
        [Unicode(false)]
        public string Nome { get; set; }

        [ForeignKey("IdEstado")]
        [InverseProperty("Cidade")]
        public virtual Estado IdEstadoNavigation { get; set; }
        [JsonIgnore]
        [InverseProperty("IdCidadeNavigation")]
        public virtual ICollection<Endereco> Endereco { get; set; }
    }
}