// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class Endereco
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idPessoa")]
        public int IdPessoa { get; set; }
        [Column("idCidade")]
        public int IdCidade { get; set; }
        [Required]
        [Column("logradouro")]
        [StringLength(256)]
        [Unicode(false)]
        public string Logradouro { get; set; }
        [Required]
        [Column("numero")]
        [StringLength(10)]
        [Unicode(false)]
        public string Numero { get; set; }
        [Column("complemento")]
        [StringLength(256)]
        [Unicode(false)]
        public string Complemento { get; set; }
        [Required]
        [Column("bairro")]
        [StringLength(256)]
        [Unicode(false)]
        public string Bairro { get; set; }
        [Required]
        [Column("cep")]
        [StringLength(8)]
        [Unicode(false)]
        public string Cep { get; set; }

        [ForeignKey("IdCidade")]
        [InverseProperty("Endereco")]
        public virtual Cidade IdCidadeNavigation { get; set; }
        [JsonIgnore]
        [ForeignKey("IdPessoa")]
        [InverseProperty("Endereco")]
        public virtual Pessoa IdPessoaNavigation { get; set; }
    }
}