// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class Fornecedores
    {
        public Fornecedores()
        {
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nomeSocial")]
        [StringLength(256)]
        [Unicode(false)]
        public string NomeSocial { get; set; }
        [Required]
        [Column("email")]
        [StringLength(256)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("cnpj")]
        [StringLength(14)]
        [Unicode(false)]
        public string Cnpj { get; set; }
        [Column("site")]
        [StringLength(256)]
        [Unicode(false)]
        public string Site { get; set; }
        [Required]
        [Column("telefone")]
        [StringLength(14)]
        [Unicode(false)]
        public string Telefone { get; set; }
        [Column("ramoAtividade")]
        [StringLength(256)]
        [Unicode(false)]
        public string RamoAtividade { get; set; }
        [Column("cep")]
        [StringLength(8)]
        [Unicode(false)]
        public string Cep { get; set; }
        [Column("numero")]
        [StringLength(8)]
        [Unicode(false)]
        public string Numero { get; set; }
        [Column("complemento")]
        [StringLength(8)]
        [Unicode(false)]
        public string Complemento { get; set; }
    }
}