// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class Funcionario
    {
        public Funcionario()
        {
            Servico = new HashSet<Servico>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idPessoa")]
        public int IdPessoa { get; set; }
        [Required]
        [Column("funcao")]
        [StringLength(256)]
        [Unicode(false)]
        public string Funcao { get; set; }

        [ForeignKey("IdPessoa")]
        [InverseProperty("Funcionario")]
        public virtual Pessoa IdPessoaNavigation { get; set; }
        [InverseProperty("IdFuncionarioNavigation")]
        public virtual ICollection<Servico> Servico { get; set; }
    }
}