// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class Pagamento
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idServico")]
        public int IdServico { get; set; }
        [Column("valor", TypeName = "decimal(18, 2)")]
        public decimal Valor { get; set; }
        [Column("situacao")]
        public int Situacao { get; set; }

        [JsonIgnore]
        [ForeignKey("IdServico")]
        [InverseProperty("Pagamento")]
        public virtual Servico IdServicoNavigation { get; set; }
    }
}