// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class PagCartao
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idPagamento")]
        public int IdPagamento { get; set; }
        [Column("parcelas")]
        public int Parcelas { get; set; }
    }
}