// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class Pessoa
    {
        public Pessoa()
        {
            Cliente = new HashSet<Cliente>();
            Endereco = new HashSet<Endereco>();
            Funcionario = new HashSet<Funcionario>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(256)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("email")]
        [StringLength(256)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("codNac")]
        [StringLength(256)]
        [Unicode(false)]
        public string CodNac { get; set; }
        [Required]
        [Column("telefone")]
        [StringLength(14)]
        [Unicode(false)]
        public string Telefone { get; set; }

        [JsonIgnore]
        [InverseProperty("IdPessoaNavigation")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [InverseProperty("IdPessoaNavigation")]
        public virtual ICollection<Endereco> Endereco { get; set; }
        [JsonIgnore]
        [InverseProperty("IdPessoaNavigation")]
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}