// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class Pet
    {
        public Pet()
        {
            Servico = new HashSet<Servico>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(256)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("idEspecie")]
        public int IdEspecie { get; set; }
        [Column("idRaca")]
        public int IdRaca { get; set; }
        [Column("idade")]
        public int Idade { get; set; }

        [ForeignKey("IdEspecie")]
        [InverseProperty("Pet")]
        public virtual Especie IdEspecieNavigation { get; set; }
        [ForeignKey("IdRaca")]
        [InverseProperty("Pet")]
        public virtual Raca IdRacaNavigation { get; set; }
        [JsonIgnore]
        [InverseProperty("IdPetNavigation")]
        public virtual ICollection<Servico> Servico { get; set; }
    }
}