// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Petshop.Entities.EntitiesContext
{
    public partial class Produto
    {
        public Produto()
        {
            ServicoProduto = new HashSet<ServicoProduto>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idCategoria")]
        public int IdCategoria { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(256)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("preco", TypeName = "decimal(18, 2)")]
        public decimal Preco { get; set; }

        [ForeignKey("IdCategoria")]
        [InverseProperty("Produto")]
        public virtual Categoria IdCategoriaNavigation { get; set; }
        [InverseProperty("IdProdutoNavigation")]
        [JsonIgnore]
        public virtual ICollection<ServicoProduto> ServicoProduto { get; set; }
    }
}